### ISSUE TITLE
Subset Selection job - + WARNING: will ignore (but maintain) values for the unknown label:

### ISSUE THREAD

**Issue by brodriguezdefrancisco** [cryoEM-CNIO/CNIO_Ctf_Ice_Thickness#1]
Hi. I am running your script and encountered this problem:

**+ WARNING: will ignore (but maintain) values for the unknown label: rlnMicrographIceThickness**

it appears in the terminal tab when using the GUI for the Subset job.

Also, need to run the printed command directly on the terminal, relion GUI keeps saying: **sh: ../../CNIO_Ctf_Ice_Thickness/ice.py: Permission denied**

And, can you give insights on the numbers from the ice thickness estimation? I see values, eg:  0.887900, 1.369840, 0.337680...

Can you help me out?

Thank you,
Borja

**Comment by nayimgr** [comment]
Hey @brodriguezdefrancisco,

About the WARNING you're getting: the selection of micrographs using "Subset selection" is not implemented yet in the RELION4 beta. It will be soon, though. In the meantime, you can use the graphic selection tool in relion_analyse.py (select the lasso tool and choose the micrographs you want, then export it using the button in the bottom left corner and import it into relion using the GUI). Also, an old-school 'awk' one liner could do the trick.

About the permissions to access the ice.py: it seems like you don't have permission to read the directory where ice.py is stored (or the ice.py file itself). Could you check that? It could also be that your file is not executable yet. You can try 'chmod u+x ice.py' to make it so.

The numbers from the ice thickness estimation are the sum of the intensities in the micrographs' CTF in the resolution range from 3.6 to 4 A (0.25 to 0.28 A⁻¹ in reciprocal). That's the region were the ice signal usually shows up! These numbers will sort your dataset nicely but are going to vary a bit in between datasets (and definitely between samples with carbon support or without carbon support). Nevertheless, we have notice that even in between datasets the numbers are quite consistent.

Thanks a lot for using our scripts! Please let us know if it finally worked for you :)

**Comment by brodriguezdefrancisco** [comment]
Hello again @nayimgr, thanks for looking at it.

I have tried it again and works. About the permissions, our IT contact solved it fast. We did not have some rights on that machine.

Interesting tool and useful!
